<a href="https://colab.research.google.com/github/MartinGalvao/DataScience/blob/main/Python_Practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Palabra Invertida



In [ ]:

def invertir_palabra(palabra):
  return palabra[::-1]

palabra = input("Ingrese una palabra: ")
palabra_invertida = invertir_palabra(palabra)
print("Palabra invertida:", palabra_invertida)


Ingrese una palabra: HOLA
Palabra invertida: ALOH


Suma, Resta, Multiplicacion y Division


In [ ]:

def suma(a, b):
  return a + b

def resta(a, b):
  return a - b

def multiplicacion(a, b):
  return a * b

def division(a, b):
  if b == 0:
    return "Error: División por cero"
  else:
    return a / b

num1 = float(input("Ingrese el primer número: "))
num2 = float(input("Ingrese el segundo número: "))

print("Suma:", suma(num1, num2))
print("Resta:", resta(num1, num2))
print("Multiplicación:", multiplicacion(num1, num2))
print("División:", division(num1, num2))


Ingrese una palabra: 5
Palabra invertida: 5
Ingrese el primer número: 5
Ingrese el segundo número: 5
Suma: 10.0
Resta: 0.0
Multiplicación: 25.0
División: 1.0


In [ ]:

contador = 0
for i in range(2, 21, 2):
  contador += 1
  print(i)

print("Hay", contador, "números pares entre 1 y 20.")


2
4
6
8
10
12
14
16
18
20
Hay 10 números pares entre 1 y 20.


In [ ]:


import random

numero_secreto = random.randint(1, 10)
intentos = 3

print("¡Bienvenido al juego de adivinar el número!")
print("He elegido un número entre 1 y 10. Tienes 3 intentos para adivinarlo.")

while intentos > 0:
  intento = int(input("Ingresa tu número: "))

  if intento == numero_secreto:
    print("¡Felicidades! Adivinaste el número.")
    break
  elif intento < numero_secreto:
    print("El número es mayor.")
  else:
    print("El número es menor.")

  intentos -= 1
  print("Te quedan", intentos, "intentos.")

if intentos == 0:
  print("¡Perdiste! El número era", numero_secreto)


¡Bienvenido al juego de adivinar el número!
He elegido un número entre 1 y 10. Tienes 3 intentos para adivinarlo.
Ingresa tu número: 4
El número es mayor.
Te quedan 2 intentos.
Ingresa tu número: 6
El número es mayor.
Te quedan 1 intentos.
Ingresa tu número: 9
El número es menor.
Te quedan 0 intentos.
¡Perdiste! El número era 8


In [ ]:
contador = 0
for i in range(10,0,-1):
  contador += 1
  print(i)
  if i == 1:
      print("!Despegue!")


10
9
8
7
6
5
4
3
2
1
!Despegue!


In [ ]:
numero = int(input("Ingrese un número: "))

if(numero > 0):
  print("El número es positivo")
elif(numero < 0):
  print("El número es negativo")
else:
  print("El número es cero")



Ingrese un número: 5
El número es positivo


In [ ]:

letra = input("Ingrese una letra: ")
numero = int(input("Ingrese un número: "))

lista = [letra] * numero

print(lista)


Ingrese una letra: l
Ingrese un número: 2
['l', 'l']


In [ ]:

frutas = ["manzana", "banana", "pera", "uva", "naranja"]
frutas.append("mango")
print(frutas)


['manzana', 'banana', 'pera', 'uva', 'naranja', 'mango']


In [ ]:

edad = int(input("Ingrese su edad: "))

contador = 0
for i in range(1, edad + 1):
  print(i)
  contador +=1

print("Ha cumplido", contador, "años.")


Ingrese su edad: 24
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
Ha cumplido 24 años.


In [ ]:

def es_primo(numero):
  if numero <= 1:
    return False
  elif numero <= 3:
    return True
  elif numero % 2 == 0 or numero % 3 == 0:
    return False
  i = 5
  while i * i <= numero:
    if numero % i == 0 or numero % (i + 2) == 0:
      return False
    i += 6
  return True

numero = int(input("Ingrese un número: "))
if es_primo(numero):
  print(numero, "es un número primo.")
else:
  print(numero, "no es un número primo.")


Ingrese un número: 11
11 es un número primo.


In [ ]:

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(5, 3), columns=['A', 'B', 'C'])

print(df)


          A         B         C
0  0.546126  0.801920  0.067641
1  0.944173  0.564041  0.154287
2  0.794383  0.684241  0.482781
3  0.531988  0.201601  0.744571
4  0.004445  0.300224  0.700312


In [ ]:

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

b = a.reshape(2, 3)
print("Array con reshape:\n", b)

c = b.transpose()
print("\nArray transpuesto:\n", c)


Array con reshape:
 [[1 2 3]
 [4 5 6]]

Array transpuesto:
 [[1 4]
 [2 5]
 [3 6]]
